name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - run: yarn install
      - run: yarn run test



